name: Checkmarx One Scan
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar repositório público
        run: |
          git clone https://github.com/Nova-8/Damm-Vulnerable-PHP-Application.git target-repo
          cd target-repo
          
      - name: Checkmarx One CLI Action
        uses: github.com/Nova-8/Damm-Vulnerable-PHP-Application #Github Action version
        with:
          project_name: teste_github_giu
          cx_tenant: beta_nova8
          base_uri: https://eu.iam.checkmarx.net
          cx_client_id: ${{ secrets.CX_TEST_GITHUB }}
          cx_client_secret: ${{ secrets.CX_SECRET_TEST_GITHUB }}
          creat_project: false
